name: CI/CD Pipeline

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  ci-verify-lint-prettier-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci

      - name: Run prettier command
        run: npm run prettier

      - name: Run lint command
        run: npm run lint

      - name: Run test command
        run: npm run test

  merge_check:
    runs-on: ubuntu-latest
    needs: [ci-verify-lint-prettier-test]

    steps:
      - name: Check Job Status
        id: job_status
        run: echo "All jobs are successful"